settings:
  env: dev
  openai:
    host: from_command_line
    key: from_command_line
  mysql:
    host: 127.0.0.1
    port: 3306
    name: askdata_dev
    user: askdata_user
    pass: askdata624@MySQL
logging:
  config: classpath:logback-dev.xml
