settings:
  env: prod
  openai:
    host: from_command_line
    key: from_command_line
  mysql:
    host: mysql.inscode.run
    port: 3306
    name: askdata_prod
    user: root
    pass: inscode
logging:
  config: classpath:logback-prod.xml
